apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: smallbiz
data:
  DB_HOST: "smallbiz-platform-db.cbneldol2tpo.ap-northeast-2.rds.amazonaws.com"
  DB_PORT: "3306"
  DB_NAME: "appdb"
